### ISSUE TITLE
animated GIF processing

### ISSUE THREAD

**Issue by tx0c** [thematters/serverless-file-post-processing#600]
some users' animated GIF avatar are very big and slowing down whole site loading:

https://assets.matters.news/avatar/b1bea2ab-112a-4cb9-8fa1-2703113751cc.gif (4MB)

needs to read all frames to convert as animated webp

API: https://sharp.pixelplumbing.com/api-constructor

```js
// Convert an animated GIF to an animated WebP
await sharp('in.gif', { animated: true }).toFile('out.webp');
```

**Comment by devformatters** [comment]
Converted it to a new issue, so closed it
