### ISSUE TITLE
[File] file-post-processing need a new way of CI deployment

### ISSUE THREAD

**Issue by tx0c** [thematters/serverless-file-post-processing#616]
tasks
- [x] research
- [x] the serverless/github-action has moved to alpine based image makes sharp unable to work. This will resolve thematters/serverless-file-post-processing#607;
- [x] `<ResponsiveImage>` for announcement cover;

refs
- [page](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-github.html)

blocked
- [issue](https://github.com/thematters/serverless-file-post-processing/issues/609)

**Comment by robertu7** [comment]
After rounds of fixing, it's caused by Serverless deployment, which will reinstall the `sharp` and makes the env not works with Lambda's.

https://github.com/thematters/serverless-file-post-processing/pull/627
