### ISSUE TITLE
[File] Reprocess old images

### ISSUE THREAD

**Issue by devformatters** [thematters/serverless-file-post-processing#629]
#### Tasks
- [ ] Some old images were not process properly. Need reprocess them all again.

**Comment by robertu7** [comment]
Looks normal now 

**Original**: https://assets-develop.matters.news/avatar/ad5fe22d-f644-4a73-8173-6650e42e4be1.gif
**144w**: https://assets-develop.matters.news/processed/144w/avatar/ad5fe22d-f644-4a73-8173-6650e42e4be1.gif

**Comment by Carolusian** [comment]
See sample reprocessed GIF files for `avatar/` and `embed/` below:

- https://matters-server-production.s3.ap-southeast-1.amazonaws.com/processed/144w/avatar/80406421-1926-467d-8bf6-36a877ed4310.gif
- https://matters-server-production.s3.ap-southeast-1.amazonaws.com/processed/144w/avatar/5e9ec9a7-9cf3-4b26-99f3-a5277b31dfb3/%E6%82%B2%E4%BC%A4-10.gif
- https://matters-server-production.s3.ap-southeast-1.amazonaws.com/processed/144w/avatar/8e665bba-9908-4aef-aed2-28a2ca7c5eec/mmexport1560302310869.gif
- https://matters-server-production.s3.ap-southeast-1.amazonaws.com/processed/540w/embed/4f5a610a-7a82-4f83-9762-148c51e71d0d.gif
- https://matters-server-production.s3.ap-southeast-1.amazonaws.com/processed/540w/embed/3cd95e01-d40b-4ba1-9b9a-b1374f559867.gif

**Comment by Carolusian** [comment]
Update lambda timeout to 5mins, and Ephemeral storage to 2048MB as 512MB may run out of space for handling temporary files. Need to monitor if there is increased cost in lambda functions.

For `imageMigrate` lambda, the API gateway timeout is 30s, so the entry point can be timeout, but the lambda shall still be successful even the API gateway timeouts
